### ISSUE TITLE
Adding support for vSphereVolume

### ISSUE THREAD

**Issue by snsumner** [upmc-enterprises/elasticsearch-operator#100]
It would be quite useful if the Elasticsearch operator add support for using vSphereVolume or NFS. I've tried tweaking it to work but have no success. 

```
[Wed Sep 20 23:32:47 core@jumpbox:~/github/snsumner/elasticsearch-operator-helm2 ] $ kubectl describe pvc es-data-es-data-standard-0 -n elasticsearch
Name:		es-data-es-data-standard-0
Namespace:	elasticsearch
StorageClass:	standard
Status:		Pending
Volume:
Labels:		component=elasticsearch
		name=es-data-standard
		role=data
Annotations:	volume.beta.kubernetes.io/storage-class=standard
		volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/vsphere-volume
Capacity:
Access Modes:
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  2m		56s		2	persistentvolume-controller			Warning		ProvisioningFailed	Failed to provision volume with StorageClass "standard": invalid option "zone" for volume plugin kubernetes.io/vsphere-volume
  2m		11s		10	persistentvolume-controller			Warning		ProvisioningFailed	Failed to provision volume with StorageClass "standard": invalid option "type" for volume plugin kubernetes.io/vsphere-volume```

**Comment by stevesloka** [comment]
What does your TPR look like? Would you be able to share that? Could you share the storage class that got created?

**Comment by snsumner** [comment]
This is what my hacked TPR looks like:

````
[Thu Sep 21 10:57:51 core@jumpbox:~/github/snsumner/elasticsearch-operator-helm2/templates ] $ cat elasticsearchcluster.yaml
{{- if not .Release.IsInstall -}}
apiVersion: enterprises.upmc.com/v1
kind: ElasticsearchCluster
metadata:
  name: {{ .Values.es_cluster_name }}
  namespace: {{ .Values.namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  master-node-replicas: {{ .Values.es_master_replicas }}
  client-node-replicas: {{ .Values.es_client_replicas }}
  data-node-replicas: {{ .Values.es_data_replicas }}
  data-volume-size: {{ .Values.volume_size }}
  elastic-search-image: "{{ .Values.es_image }}:{{ .Values.es_tag }}"
  java-options: "-Xms{{ .Values.java_xms }} -Xmx{{ .Values.java_xmx }}"
  smapshot:
    scheduler-enabled: {{ .Values.schedule_snapshot }}
    bucket-name: {{ .Values.bucket_name }}
    cron-schedule: '{{ .Values.cron_schedule }}'
  storage:
    storage-class-provisioner: kubernetes.io/vsphere-volume
    type: fast
  zones: []
{{- end -}}
```
I've tried with or without Type defined.

This is what the storage class that got created looks like:

```
[Thu Sep 21 10:56:19 core@jumpbox:~/github/snsumner/elasticsearch-operator-helm2 ] $ kubectl get sc
NAME                 TYPE
etcd-backup-gce-pd   kubernetes.io/gce-pd
fast (default)       kubernetes.io/vsphere-volume
standard             kubernetes.io/vsphere-volume
[Thu Sep 21 10:56:23 core@jumpbox:~/github/snsumner/elasticsearch-operator-helm2 ] $ kubectl describe sc standard
Name:		standard
IsDefaultClass:	No
Annotations:	<none>
Provisioner:	kubernetes.io/vsphere-volume
Parameters:	type=fast,zone=standard
Events:		<none>
```
