### ISSUE TITLE
Elasticsearch startup fails with 'failed to obtain data locks'

### ISSUE THREAD

**Issue by dustinchilson** [upmc-enterprises/elasticsearch-operator#117]
I've been experimenting with the azure example and am getting the above issue.

Could be related to pires/kubernetes-elasticsearch-cluster#145

```YAML
apiVersion: enterprises.upmc.com/v1
kind: ElasticsearchCluster
metadata:
  name: graylog-es
spec:
  client-node-replicas: 1
  master-node-replicas: 3
  data-node-replicas: 6
  network-host: 0.0.0.0
  zones: []
  data-volume-size: 10Gi
  java-options: "-Xms256m -Xmx256m"
  snapshot:
    scheduler-enabled: false
    bucket-name: elasticsnapshots99
    cron-schedule: "@every 2m"
  storage:
    storage-class: default
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 512Mi
      cpu: '1'
```

Thanks for any direction you might be able to give me.
