### ISSUE TITLE
Disabling snapshotting to AWS

### ISSUE THREAD

**Issue by selvik** [upmc-enterprises/elasticsearch-operator#125]
I will be running this operator in my local Kubernetes cluster.  Could you please tell me how I can disable snapshotting to AWS?  Would it be sufficient to remove these config options from the elastic cluster's manifest file or would I have to make any code changes?

``` 
zones:
  - us-east-1c
  - us-east-1d
  - us-east-1e
  data-volume-size: 10Gi
  snapshot:
    scheduler-enabled: false
    bucket-name: elasticsnapshots99
    cron-schedule: "@every 2m"
  storage:
    type: gp2
    storage-class-provisioner: kubernetes.io/aws-ebs
```
