### ISSUE TITLE
Elastic search master node volume size

### ISSUE THREAD

**Issue by andreimc** [upmc-enterprises/elasticsearch-operator#163]
Basically the 

  data-volume-size gets used in the masters as well. 

This is a huge waster since the masters don't actually need that much persistent disk, since they don't store a lot of data.

This should be configured separately so should JVM options and resources. 

Probably the best thing to do is go something like:
```
---
client: 
  zones:
  - us-west-2a
  - us-west-2b
  - us-west-2c
  replicas: 3
  disk-size: 1Gi
  java-options: "-Xms512m -Xmx512m"
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1024Mi
      cpu: '1'
master:
  zones:
  - us-west-2a
  - us-west-2b
  - us-west-2c
  replicas: 3
  disk-size: 1Gi
  java-options: "-Xms512m -Xmx512m"
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1024Mi
      cpu: '1'
data:
    name: data
    role: data
    is-node-master: false
    zones:
  - us-west-2a
  - us-west-2b
  - us-west-2c
  replicas: 3
  disk-size: 1Gi
  java-options: "-Xms512m -Xmx512m"
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1024Mi
      cpu: '1'
global:
  storage:
     type: gp2
     storage-class-provisioner: kubernetes.io/aws-ebs
```

this sort of stuff would be a lot more flexible
