### ISSUE TITLE
Disable TLS on ES while using 6.1.3_0

### ISSUE THREAD

**Issue by neurot1cal** [upmc-enterprises/elasticsearch-operator#204]
Is there a way currently to disable TLS on the Elasticsearch endpoint only, while using the most recent image? I see some older issues and threads saying this is possible using some older images - would like to avoid using that.

I'm terminating TLS on my Ingress, and would love to leave communication from Fluentd/Fluentbit to HTTP only within the cluster. Sorry if I'm missing something obvious somewhere, but this is driving me mad! 

Great job on the operator :)

**Comment by stevesloka** [comment]
Hey @neurot1cal I think we've got this all fixed up right now in head. I need to make a job to build a `:master` tag so you can test latest changes easier.

**Comment by stevesloka** [comment]
Ok `:master` tags for the operator are getting built automatically now. Please give it a try and let me know how it goes.

**Comment by neurot1cal** [comment]
@stevesloka Strange... Getting crashloop backoff when trying to start up the elasticsearch-operator container;

```
helm install --name elasticsearch-operator es-operator/elasticsearch-operator --namespace logging -f operator-values.yaml
```

operator-values.yaml
```
# Default values for elasticsearch-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: upmcenterprises/elasticsearch-operator
  tag: 0.0.12
  pullPolicy: Always
#  pullSecret:
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
rbac:
  enabled: false
```

```
☁  operator [features/outputdirs] ⚡ k describe -n logging po/elasticsearch-operator-5c9c444f5f-dr5xg
Name:           elasticsearch-operator-5c9c444f5f-dr5xg
Namespace:      logging
Node:           k8s-linuxpool1-17595707-4/10.240.0.66
Start Time:     Wed, 23 May 2018 09:33:05 -0700
Labels:         name=elasticsearch-operator
                pod-template-hash=1757000919
                release=elasticsearch-operator
Annotations:    <none>
Status:         Running
IP:             10.240.0.69
Controlled By:  ReplicaSet/elasticsearch-operator-5c9c444f5f
Containers:
  elasticsearch-operator:
    Container ID:   docker://2796ff37ec50fc26762f1de31cc2a3634c39f0df721a491fb7703e5f6e72a47c
    Image:          upmcenterprises/elasticsearch-operator:0.0.12
    Image ID:       docker-pullable://upmcenterprises/elasticsearch-operator@sha256:4050e6cb608ddc77a561232fadbfc12e74006f8409e46f77f7f4abff33660411
    Port:           8000/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Wed, 23 May 2018 09:34:43 -0700
      Finished:     Wed, 23 May 2018 09:34:44 -0700
    Ready:          False
    Restart Count:  4
    Limits:
      cpu:     100m
      memory:  128Mi
    Requests:
      cpu:      100m
      memory:   128Mi
    Liveness:   http-get http://:8000/live delay=10s timeout=10s period=10s #success=1 #failure=3
    Readiness:  http-get http://:8000/ready delay=10s timeout=5s period=10s #success=1 #failure=3
    Environment:
      NAMESPACE:  logging (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-zph62 (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  default-token-zph62:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-zph62
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason                 Age              From                                Message
  ----     ------                 ----             ----                                -------
  Normal   Scheduled              3m               default-scheduler                   Successfully assigned elasticsearch-operator-5c9c444f5f-dr5xg to k8s-linuxpool1-17595707-4
  Normal   SuccessfulMountVolume  3m               kubelet, k8s-linuxpool1-17595707-4  MountVolume.SetUp succeeded for volume "default-token-zph62"
  Normal   Pulling                2m (x4 over 3m)  kubelet, k8s-linuxpool1-17595707-4  pulling image "upmcenterprises/elasticsearch-operator:0.0.12"
  Normal   Pulled                 2m (x4 over 2m)  kubelet, k8s-linuxpool1-17595707-4  Successfully pulled image "upmcenterprises/elasticsearch-operator:0.0.12"
  Normal   Created                2m (x4 over 2m)  kubelet, k8s-linuxpool1-17595707-4  Created container
  Normal   Started                2m (x4 over 2m)  kubelet, k8s-linuxpool1-17595707-4  Started container
  Warning  BackOff                1m (x8 over 2m)  kubelet, k8s-linuxpool1-17595707-4  Back-off restarting failed container
```

**Comment by neurot1cal** [comment]
Durp - Left our rbac `enabled: true`. :)

**Comment by neurot1cal** [comment]
@stevesloka es-client pods are in CrashLoopBackOff;

![image](https://user-images.githubusercontent.com/11523744/40439527-06493770-5e70-11e8-9470-3bf146cf6b63.png)

**Comment by neurot1cal** [comment]
@stevesloka Things are spun up now, but it looks like it's still using HTTPS for 9200 on the client nodes;

![image](https://user-images.githubusercontent.com/11523744/40445286-8c6f9e92-5e80-11e8-9ccf-03b217f648b2.png)

![image](https://user-images.githubusercontent.com/11523744/40445274-856fd85a-5e80-11e8-9a03-485a3b504f28.png)

![image](https://user-images.githubusercontent.com/11523744/40445306-9d4637bc-5e80-11e8-91df-a650d21ae22c.png)

Here's my values.yaml;

![image](https://user-images.githubusercontent.com/11523744/40445322-a7f12e4c-5e80-11e8-8ff8-7e8bdecd2884.png)

**Comment by stevesloka** [comment]
Can you test again? I just pushed another PR.

**Comment by neurot1cal** [comment]
Same deal. Does my chart and install sequence look right?

![image](https://user-images.githubusercontent.com/11523744/40524947-44c6f4b0-5f92-11e8-9f9d-8295b8823b63.png)

```
#Add repo
helm repo add es-operator https://raw.githubusercontent.com/upmc-enterprises/elasticsearch-operator/master/charts/

#Install ES operator
helm install --name elasticsearch-operator es-operator/elasticsearch-operator --namespace logging -f operator-values.yaml
helm upgrade elasticsearch-operator es-operator/elasticsearch-operator -f operator-values.yaml

#Install ES cluster
helm install --name elasticsearch es-operator/elasticsearch --namespace logging -f elasticsearch-values.yaml
helm upgrade elasticsearch es-operator/elasticsearch --namespace logging -f elasticsearch-values.yaml
```

![image](https://user-images.githubusercontent.com/11523744/40524969-5d7fb8ac-5f92-11e8-89f2-c0f934f1999b.png)

![image](https://user-images.githubusercontent.com/11523744/40524976-62ba11e6-5f92-11e8-9a58-2a16cda4d821.png)

**Comment by gianrubio** [comment]
Did you delete all the objects + elasticsearch crd before installing it again? Seems like ssl configuration are cached somewhere

**Comment by neurot1cal** [comment]
@gianrubio Good catch, `helm delete --purge` doesnt actually delete the CRD. Trying again...

**Comment by stevesloka** [comment]
also can you take helm out of the picture? Just create the operator and then the crd to test.

**Comment by neurot1cal** [comment]
@stevesloka Ok. Still not working with helm. Here's my approach, I'm creating the controller and then applying the es-cluster-azure.yaml in /examples and it's not building the clusters. Any ideas?

controller.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch-operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: elasticsearch-operator
rules:
- apiGroups: ["extensions"]
  resources: ["deployments", "replicasets", "daemonsets"]
  verbs: ["create", "get", "update", "delete", "list"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "get", "update", "delete", "list"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "create", "delete", "deletecollection"]
- apiGroups: [""]
  resources: ["persistentvolumes", "persistentvolumeclaims", "services", "secrets", "configmaps"] 
  verbs: ["create", "get", "update", "delete", "list"]
- apiGroups: ["batch"]
  resources: ["cronjobs", "jobs"]
  verbs: ["create", "get", "deletecollection", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["apps"]
  resources: ["statefulsets", "deployments"]
  verbs: ["*"]
- apiGroups: ["enterprises.upmc.com"]
  resources: ["elasticsearchclusters"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: elasticsearch-operator
  namespace: operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elasticsearch-operator
subjects:
- kind: ServiceAccount
  name: elasticsearch-operator
  namespace: operator
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-operator
  namespace: operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: elasticsearch-operator
    spec:
      containers:
      - name: operator
        image: upmcenterprises/elasticsearch-operator:0.1.0
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8000
          name: http
        livenessProbe:
          httpGet:
            path: /live
            port: 8000
          initialDelaySeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          timeoutSeconds: 5
      serviceAccount: elasticsearch-operator
```

es-cluster-azure.yaml
```
apiVersion: enterprises.upmc.com/v1
kind: ElasticsearchCluster
metadata:
  name: es-cluster
spec:
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.3
  cerebro:
    image: upmcenterprises/cerebro:0.6.8
  elastic-search-image: upmcenterprises/docker-elasticsearch-kubernetes:6.1.3_0
  client-node-replicas: 3
  master-node-replicas: 2
  data-node-replicas: 3
  network-host: []
  zones: []
  data-volume-size: 10Gi
  java-options: "-Xms1024m -Xmx1024m"
  use-ssl: false
  snapshot: []
  storage:
    storage-class: default
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1024Mi
      cpu: '1'
```

```
kubectl create ns operator
kubectl apply -f ./controller.yaml -n operator
kubectl apply -f ./es-cluster-azure.yaml -n operator
```

```
☁  k get pods -n operator
NAME                                      READY     STATUS    RESTARTS   AGE
elasticsearch-operator-7d96cf6f7d-86zr4   1/1       Running   0          11m
```
