### ISSUE TITLE
Master re-election delay (10+seconds) and outage

### ISSUE THREAD

**Issue by nabadger** [upmc-enterprises/elasticsearch-operator#241]
This is actually something we can re-produce (and are struggling to understand) on a manually deployed ES cluster, but I've just tested it with the your operator as well, and it exhibits the same issue.

Generally speaking we would expect a delay of a few seconds during re-election, but when deploying ES on K8s we are seeing master re-elections take between 10 and 30s.

Config:
```
apiVersion: enterprises.upmc.com/v1
kind: ElasticsearchCluster
metadata:
  name: example-es-cluster
spec:
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.3
  cerebro:
    image: upmcenterprises/cerebro:0.6.8
  elastic-search-image: upmcenterprises/docker-elasticsearch-kubernetes:6.1.3_0
  client-node-replicas: 1
  master-node-replicas: 3
  data-node-replicas: 1
  network-host: 0.0.0.0
  zones: []
  data-volume-size: 10Gi
  java-options: "-Xms512m -Xmx512m"
  snapshot:
    scheduler-enabled: false
    bucket-name: elasticsnapshots99
    cron-schedule: "@every 2m"
    image: upmcenterprises/elasticsearch-cron:0.0.4
  storage:
    storage-class: do-block-storage
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1024Mi
      cpu: '1'
```

To test this, I have 3 masters, and a single data and client instance.

If I watch the status of `curl https://localhost:9200/_cat/nodes` on the client or data node, I can monitor which is the current master.

If I `kubectl exec` into  the elected master and `kill 1` (the java process), it dies as expected, and master re-election typically happens under 3 seconds.

If I however kill the pod of the running master (`kubectl delete pod <podname>`), we don't see any master re-election happen for typically 10 to 30 seconds. It actually looks like it waits for the new pod to be created, and for the health probes to succeed.

During this phase, the curl command will fail (since there's no elected  master).

I suspect this is related to various timeouts (both k8s and ES) but having a hard time figuring out which ones. We also think it might be DNS caching related.

Do you know if this is expected behaviour?
